version: "3.9"

services:
     profile-vy-02:
          container_name: profile-fe
          build:
               context: .
               dockerfile: Dockerfile
          volumes:
               - ".:/app"
               - "/app/node_modules"
          ports:
               - "6000:80"
          environment:
               - NODE_ENV=development
