//Redux
const FETCHED_LESSOR = "FETCHED_LESSOR";
const FETCHED_LIST_LESSOR = "FETCHED_LIST_LESSOR";
const FETCHED_APARTMENT = "FETCHED_APARTMENT";
const SET_CHECK_IN_DATE = "GET_CHECK_IN_DATE";
const SET_CHECK_OUT_DATE = "GET_CHECK_OUT_DATE";
const SET_REQUIREMENT = "SET_REQUIREMENT";
// Others

export {
	FETCHED_LESSOR,
	FETCHED_LIST_LESSOR,
	FETCHED_APARTMENT,
	SET_CHECK_IN_DATE,
	SET_CHECK_OUT_DATE,
	SET_REQUIREMENT,
};
